### ISSUE TITLE
please update this

### ISSUE THREAD

**Issue by webineh** [magkopian/php-infinite-multi-level-comments#1]
hello this a nice comment system please upgrade..

**Comment by magkopian** [comment]
The code may have to be updated for a while, though neither seem to be any open issues about something that is not working the way it should be.

The reason I haven't added any new features, is mainly because nobody seems to be using it and I have more important things to work with.

**Comment by ipsmile** [comment]
Hello,  I followed your instructions and installed the package through composer. After moved the `Config.template.php` file to `src/classes/Config.php`. Open up the debug.php, however, it doesn't work. I traced the code through debugging facility. The problem seems to be the the Config.php is considered missing. In fact the Config.php is present in the src/classes directory. Thus, the database, user, password are not resolved properly to connect to mysql. Just like to report the issue here. Thx.
